# =============================================================================
# PROVISIONAL - Local development environment only
# Not intended for production use
# =============================================================================
name: delfos-project

include:
  - ./notifications/compose.yaml
  - ./data_ingestion/docker-compose.yml
  - ./processing/docker-compose.yaml
  - ./orchestration/docker-compose.yaml
