services:
  
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "9090:8080"

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  spark-streaming:
    image: apache/spark:3.5.1
    container_name: spark-streaming
    restart: unless-stopped
    depends_on:
      - kafka
      - spark-master
    volumes:
      - ./spark:/app
    environment:
      - HOME=/tmp
    command: >
      bash -c "pip install psycopg2-binary &&
      /opt/spark/bin/spark-submit
      --total-executor-cores 2
      --executor-cores 2
      --conf spark.scheduler.mode=FAIR
      --conf spark.sql.shuffle.partitions=4
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.7.3
      --master spark://spark-master:7077
      /app/spark-streaming.py"
  spark-streaming-price-changes:
    image: apache/spark:3.5.1
    container_name: spark-price-changes
    restart: unless-stopped
    depends_on:
      - kafka
      - spark-master
      - postgres
    volumes:
      - ./spark:/app
    environment:
      - HOME=/tmp
    command: >
      bash -c "
      /opt/spark/bin/spark-submit
      --total-executor-cores 2
      --executor-cores 2
      --conf spark.scheduler.mode=FAIR
      --conf spark.sql.shuffle.partitions=4
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.7.3
      --master spark://spark-master:7077
      /app/spark-streaming-price-changes.py
      "
  
  spark-streaming-users:
    image: apache/spark:3.5.1
    container_name: spark-users
    restart: unless-stopped
    depends_on:
      - kafka
      - spark-master
      - postgres
    volumes:
      - ./spark:/app
    environment:
      - HOME=/tmp
    command: >
      bash -c "pip install psycopg2-binary &&
      /opt/spark/bin/spark-submit
      --total-executor-cores 2
      --executor-cores 2
      --conf spark.scheduler.mode=FAIR
      --conf spark.sql.shuffle.partitions=4
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.7.3
      --master spark://spark-master:7077
      /app/spark-streaming-users.py"
  
  spark-streaming-suspicious:
    image: apache/spark:3.5.1
    container_name: spark-suspicious
    restart: unless-stopped
    depends_on:
      - kafka
      - spark-master
      - postgres
    volumes:
      - ./spark:/app
    environment:
      - HOME=/tmp
    command: >
      bash -c "pip install psycopg2-binary requests &&
      /opt/spark/bin/spark-submit
      --total-executor-cores 2
      --executor-cores 2
      --conf spark.scheduler.mode=FAIR
      --conf spark.sql.shuffle.partitions=4
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.7.3
      --master spark://spark-master:7077
      /app/spark-streaming-trade-suspicious.py"
  
  postgres:
    build: .
    container_name: postgres
    environment:
      POSTGRES_DB: markets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./init-db:/docker-entrypoint-initdb.d