
services:
  # El asistente de Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # El transportista de datos
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Este es el servicio de almacenamiento (MinIO)
  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - "9000:9000"    # Puerto para que los scripts manden datos
      - "9001:9001"    # Puerto para que se entre a ver los archivos (Consola)
    environment:
      MINIO_ROOT_USER: admin           
      MINIO_ROOT_PASSWORD: administrador
    volumes:
      - ./datos_minio:/data           # Esto guarda los datos en una carpeta real del pc
    command: server /data --console-address ":9001"