services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  # CAPA BRONCE (NoSQL)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=administrador
    volumes:
      - ../datos_mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=administrador
      - ME_CONFIG_MONGODB_URL=mongodb://admin:administrador@mongodb:27017/

  # CAPA ORO (Relacional)
  postgres_gold:
    image: postgres:15
    container_name: postgres_gold
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=administrador
      - POSTGRES_DB=capa_oro
    ports:
      - "5432:5432"
    volumes:
      - ../datos_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gold
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=administrador
    ports:
      - "5050:80"
    depends_on:
      - postgres_gold
  
  # actúa como el Broker
  redis_broker:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"

  # nterfaz web para ver el estado de las tareas
  flower:
    image: mher/flower
    container_name: flower_monitor
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis_broker:6379/0
    depends_on:
      - redis_broker

